### ISSUE TITLE
Utility package

### ISSUE THREAD

**Issue by z0w0** [switchface/helm#79]
There's a demand for utility functions that don't necessarily play well with the idea of Helm being an (almost) 1<>1 port of Elm to Haskell. There should be a separate package for these sort of functions / types / classes, etc. The original animation and transition modules that were removed should also be readded to this. See #78 for an example of another function that could be added.

**Comment by kasbah** [comment]
Looks like this is now here: [hiilohlin/helm-extras](https://github.com/niilohlin/helm-extras), if any one comes here looking for it.
