### ISSUE TITLE
The sdl2 version bounds are too loose on hackage since 0.6.0.

### ISSUE THREAD

**Issue by ekmett** [switchface/helm#86]
The contents of [`Graphics.UI.SDL.Enum`](http://hackage.haskell.org/package/sdl2-1.3.0/docs/Graphics-UI-SDL-Enum.html) rather radically changed in 1.3.0, and the < 2 version bound you've been using on hackage since helm 0.6.0 doesn't work.

You can now change these retroactively on hackage by using the edit package description to lower the upper bound to < 1.3. If you did this before pushing a new version, you'd have a lot fewer user install problems.

**Comment by kasbah** [comment]
Going forward it was fixed with #74. I don't have access to the hackage package so @z0w0 will need to do the retroactive edit.

**Comment by z0w0** [comment]
I've deprecated the other packages and uploaded 0.7.1 which contains the corrected version bounds.

**Comment by ekmett** [comment]
Sadly, deprecation doesn't _actually_ work on hackage at the moment, so 0.6.0 and 0.6.1 can still be selected by the solver unless you cap their versions as well.

**Comment by z0w0** [comment]
Ugh, absolute bummer. Is there not even a warning saying it's deprecated!?

On Mon, Jan 5, 2015 at 9:01 AM, Edward Kmett <notifications@github.com>
wrote:

> Sadly, deprecation doesn't *actually* work on hackage at the moment, so
> 0.6.0 and 0.6.1 can still be selected by the solver unless you cap their
> versions as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchface/helm/issues/86#issuecomment-68653707>.
>



-- 
Zack Corr
*z0w0.me <http://z0w0.me>*

**Comment by ekmett** [comment]
It basically does nothing at this point. You _might_ get a deprecation warning on the page for the haddocks or something, but I've never seen it.
