### ISSUE TITLE
Monad transformer stack over Signal?

### ISSUE THREAD

**Issue by isovector** [switchface/helm#94]
Is it possible to get a monad transformer stack over `Signal`? I want to pass around the current `Level` in a `Reader`, but can't seem to figure out how to do it.

There might be a better way of doing this, like maybe making a `Signal Level` and thread it through, but this doesn't seem particularly fun to write, and unlikely to play nicely with `foldp`. 

Am I missing something? FRP is hard =) 

Cheers!

**Comment by kasbah** [comment]
The Helm `Signal`, like Elm's is not a monad. This is a conscious design decision. Check out elm-lang/elm-compiler#413.

If you drop down a level into Elerea, you might be able to do what you want to do. On the other hand sticking to applicative signals will likely give your application a cleaner design.

**Comment by isovector** [comment]
Yeah, I had a moment of epiphany last night -- I should probably encapsulate my current signal-level stuff into a record for game state. As usual with Haskell, when I find myself being unable to implement my first thought, it turns out to be the wrong approach. 

Thanks for your time!
